name: buffet_app
description: POS BuffetApp (offline-first) multiplataforma.
publish_to: 'none'
version: 1.3.1+15

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.2
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.5.1
  provider: ^6.1.2
  # share_plus v12 requiere AGP/Kotlin muy recientes. Fijamos a 11.x para compatibilidad con el proyecto actual.
  share_plus: ^11.1.0
  open_filex: ^4.0.2
  file_saver: ^0.2.12
  intl: ^0.20.2
  # Impresión PREVIEW (luego podemos agregar printing/pdf si lo preferís)
  printing: ^5.13.3
  pdf: ^3.11.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.3.1
  device_info_plus: ^10.1.0
  image_picker: ^1.1.2
  image: ^4.2.0
  supabase_flutter: ^2.3.4
  fl_chart: ^0.66.2
  win32: ^5.5.4
  excel: ^2.1.0
  file_picker: ^8.1.6
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/sql/
    - assets/sync/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon_foreground.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon_foreground.png
  windows:
    generate: true
    image_path: assets/icons/app_icon_foreground.png
