name: buffet_app
description: POS BuffetApp (offline-first) multiplataforma.
publish_to: 'none'
version: 1.3.2+16

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.7+1
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.5.3
  provider: ^6.1.2
  # share_plus v12 requiere AGP/Kotlin muy recientes. Fijamos a 11.x para compatibilidad con el proyecto actual.
  share_plus: ^11.1.0
  open_filex: ^4.0.2
  file_saver: ^0.3.1
  intl: ^0.20.2
  # Impresión PREVIEW (luego podemos agregar printing/pdf si lo preferís)
  printing: ^5.13.3
  pdf: ^3.11.1
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  dio: ^5.9.1
  image_picker: ^1.2.1
  image: ^4.3.0
  supabase_flutter: ^2.12.0
  fl_chart: ^1.1.1
  win32: ^5.15.0
  excel: ^2.1.0
  file_picker: ^10.3.10
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/sql/
    - assets/sync/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon_foreground.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon_foreground.png
  windows:
    generate: true
    image_path: assets/icons/app_icon_foreground.png
